### ISSUE TITLE
Improve record indentation

### ISSUE THREAD

**Issue by luntain** [iquiw/hyai#15]
When I define a record data type or value of a record data type per the style guide,  I would like the cursor to be under the previous comma/opening brace.

Instead, this mode places the cursor under the first character of the type or value assigned to a field. I see that this behavior is tested for:

```
    Given the buffer is empty
    When I insert:
    """
    person = Person
        { firstName = "John"
    """
    And I call hyai-indent-candidates at the current point
    Then indent candidates are "(18)"

    Given the buffer is empty
    When I insert:
    """
    person = Person
        { firstName = "John"
        , lastName = "Smith"
    """
    And I call hyai-indent-candidates at the current point
    Then indent candidates are "(17)"

```

How about:

```
    Given the buffer is empty
    When I insert:
    """
    person = Person
        { firstName = "John"
    """
    And I call hyai-indent-candidates at the current point
    Then indent candidates are "(4 18)"

    Given the buffer is empty
    When I insert:
    """
    person = Person
        { firstName = "John"
        , lastName = "Smith"
    """
    And I call hyai-indent-candidates at the current point
    Then indent candidates are "(4 17)"

```

**Comment by iquiw** [comment]
In this case, if `,` or `}` is entered in the next line, the indent will be `4`. Isn't is sufficient?

**Comment by luntain** [comment]
That would be sufficient. Is it what happens now? I don't see that behavior in my setup.

**Comment by iquiw** [comment]
It isn't automatically done, <kbd>TAB</kbd> is required.

It may be possible to achieve automatic indent by `electric-indent-mode`.
But `haskell-mode` [disables it](https://github.com/haskell/haskell-mode/blob/9018ad5cac0b1b1b5e0a51586027fb0ca4076b1a/haskell-mode.el#L833-L836) now for some reason, so it may cause unexpected behavior.

Below is untested code.

``` emacs-lisp
(add-hook 'haskell-mode-hook
  (lambda ()
    (setq electric-indent-inhibit nil)
    (setq electric-indent-chars '(?, ?\})))
```

**Comment by luntain** [comment]
I didn't press TAB. That helps.
